### ISSUE TITLE
Issues Playing on Rift S

### ISSUE THREAD

**Issue by Distant075** [teddybear082/CrueltySquadVR-Modloader#1]
So far, I've played up to Androgen Assault, and have found these problems:

General Issues - 
Fall damage is extremely strict, especially around ladders
Bolt ACR didn't work (Only tried it once on Androgen Assault)
Light rays in room past Bouncy Castle target in Androgen Assault can be walked up and will kill you if you hit the roof

Crashes/Softlocks - 
Crash on Paradise when trying to use funkgrunters at the same time as dying to fall damage
Opening Oculus menu constantly flashes one half of the screen on and off and requires a reset to fix
Crashes when returning to level select and trying to enter a new level after playing a few in a row. 
(Specifically the crashes happened when trying to enter Paradise after beating CSHQ and Pharmoko as well as entering Androgen Assault after Paradise and Sin Space)
Stuck in loading after failing Androgen Assault, changing audio settings (Probably unrelated? All I changed was master volume), then attempting to reenter Androgen

Some of these issues are likely specific to the Rift S, since Oculus doesn't really support it anymore, but I figured I may as well report them just in case. I may also be able to fix some of them by using -overridenohmd in Steam and using SteamVR, but I haven't tested that yet

**Comment by teddybear082** [comment]
Thanks so much for taking the time to let me know! Unfortunately, yes, I don't have a Rift S, and even though I use Quest, I use Virtual Desktop 99% of the time because I hate Oculus's VR software and it has so many issues.  So something like opening the Oculus menu my guess is I can't fix.

The specifics on the crashes is helpful; I get seemingly random crashes too but always possible there is something I can do to fix.

Fall damage is an easy modifier and I can fix that in a patch at some point.

Bolt ACR I have definitely used before - the radiation gun.  So I will check it out in Androgen assault specifically, and if I can get to the light rays without dying I will check that out haha.

Thanks again for your time if you find other stuff please let me know.  You're helping a lot of other people that probably will just be frustrated rather than report, which I don't want if I can help it.

**Comment by SpencerBinXia** [comment]
Seconded on the fall damage, definitely way too harsh compared to flat

**Comment by teddybear082** [comment]
> Seconded on the fall damage, definitely way too harsh compared to flat


> Fall damage is extremely strict, especially around ladders

Can you guys try replacing your vr-mod-files folder in your mods folder in AppData with this one and see if this is good for fall damage or if the threshold should still be higher?


[cs-vr-mod-vr-files.zip](https://github.com/teddybear082/CrueltySquadVR-Modloader/files/10888451/cs-vr-mod-vr-files.zip)

**Comment by SpencerBinXia** [comment]
Hey, its definitely less harsh but still a bit too harsh vs flat.

I think a good way to test this is via the alley drop in Pharmakokinetiks, in the base game it leaves you with exactly 54 health. This currently kills you in VR.

![cs1](https://user-images.githubusercontent.com/25407980/222920201-dce91ee7-6ff7-4b54-bb30-059325becd45.JPG)
![cs2](https://user-images.githubusercontent.com/25407980/222920206-f021fa7e-fb10-4660-bd29-2ebadc4e70c2.JPG)

**Comment by teddybear082** [comment]
I will go ahead and close this issue as other than crashing which is noted in the other issue the rest has been addressed with the 1.4 beta update.
