### ISSUE TITLE
Controller Input Requests + Other Issues/Comments.

### ISSUE THREAD

**Issue by SpencerBinXia** [teddybear082/CrueltySquadVR-Modloader#2]
Hey, first off really appreciate the work you've put into this mod! When I first tried Cruelty Squad I kept thinking how much better the game would be in VR and now we actually have it thanks to you, swinging around with the Grappendix in VR is really something. There are so many different mechanics at work here its insane. 

Issues I noticed:
~- Current bindings for Grappendix are tough as its difficult to hold down Grappendix and also jump at the same time (like for the gunkbooster double jump). Maybe you could swap the left controller joystick press (doesn't do much besides go back in menus) with the Grappendix button?~
~- Have an option to disable controller rotation/turning in the options, since jump is also on the joystick so it can be annoying to accidentally turn when I didn't want to.~
~- Guns "sliding" off your hand position when the gun is close to colliding with walls/objects, definitely painful if you're aiming down sights. I think I would prefer clipping to this.~
~- As the other issue mentioned, fall damage is way too extreme compared to the flat game~
~- Dialogue box can sometimes be overly transparent and difficult to read, seems to depend on how dark the background is (darker = worse)~
~- in-game VR options don't save on game restart, would be a nice to have if they did~
~- Weapon scope view distance is significantly behind normal view distance (most obvious on Paradise)~
~- gunkbooster puddle spawns where your weapon cursor is pointing instead of below your feet~
- Crashing is definitely pretty bad currently, happens moreso when attempting to load levels but ~has also happened rarely mid-gameplay~
- explosives like the anti-armor rocket launcher don't launch you like they do in regular game
- even with AI NPC hack off I can see that sometimes the AI is stuck not reacting like they would be in the regular game. it seems very minor though, for the most part the AI is much better with the hack off then on.

**Comment by teddybear082** [comment]
Thank you!!

-Yes I will look into a different bind for Grappendix! This has been mentioned before. Incidentally, I have to see if that will work in the first place (jumping while grappling).  In the meantime you can swing your arms up physically to jump as well rather than using the stick (swing both arms up in an upward motion).

-Yes, it should be easy to make an option to turn off turning, I can put that in the next update.

-Maybe someday I will create an in- game remapping, I'm just not there yet.  I have the infrastructure with the way I coded the game but also it will be about preventing conflicts....

-Yeah the crashing is annoying not sure why it happens. Feel free to respond to this thread with your logs right after it crashes. You can find them in the logs folder of AppData.  Maybe with enough people testing and sending logs I will find some sort of pattern.

-will fix fall damage, that is an easy change to a variable, appreciate the feedback.

-Interestingly the gun behavior "just happens" the way the base game is programmed when they hit a wall, you're right, in one way its cool - they don't go through walls - in other ways it is annoying.  I'll see if there is anything to stop that.

**Comment by SpencerBinXia** [comment]
Will add more comments here for notable issues to bring up:

- Weapon scope view distance is significantly behind normal view distance (most obvious on Paradise)

**Comment by teddybear082** [comment]
Closing this thread as all issues have been addressed except known issues that I don't plan to change for now, and I will create a separate thread for known issues.  Open new threads for any bugs found on release 1.0. Thanks!!
